name: Assemble Build

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: Build Linux
    uses: ./.github/workflows/linux_compile.yml

  build_windows:
    name: Build Windows
    uses: ./.github/workflows/windows_compile.yml
    
  assemble_build:
    needs: [build_linux, build_windows]
    name: Assemble Build
    runs-on:
      ubuntu-latest

    steps:
      - name: Checkout Game Files
        uses: actions/checkout@v4
        with:
          repository: fortressforever-2013/fortressforever
          path: fortressforever
          ref: ${{ vars.GAME_BRANCH }}

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ff_linux
          path: fortressforever/bin

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ff_windows
          path: fortressforever/bin
      - name: Update Server Bin Link
        run: |
          cp -rf fortressforever/bin/server.so fortressforever/bin/server_srv.so

      - name: Remove Extra Files
        run: |
          cd fortressforever
          rm -rf .git .gitignore .gitattributes bin/*.pdb bin/*.dbg

      - name: Download VPKEdit
        run: |
          wget -O VPKEdit.zip https://github.com/craftablescience/VPKEdit/releases/latest/download/VPKEdit-Linux-Standalone-CLI-gcc-Release.zip
          unzip VPKEdit.zip
          chmod +x vpkeditcli
          python3 pack_vpk.py

      - name: Archive Game
        run: |
          tar -I 'gzip -9' -cvf fortressforever.tar.gz fortressforever

      - name: Release to Drafts
        uses: softprops/action-gh-release@v2
        with:
          name: Fortress Forever 2013 ${{ vars.VERSION }}
          tag_name: ${{ vars.VERSION }}
          files: fortressforever.tar.gz
          make_latest: true
          draft: true