name: Linux Compiler

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_linux:
    name: Build Linux Binaries
    runs-on:
      ubuntu-22.04
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fortressforever-2013/fortressforever-src
          path: ff-src
          ref: ${{ vars.CODE_BRANCH }}

      - name: Create Project
        working-directory: ff-src/mp/src
        run: devtools/bin/vpc /ff +game /mksln Game_FF

      - name: Build Project
        working-directory: ff-src/mp/src
        env:
          CC: gcc-10
          CXX: g++-10
        run: make -f Game_FF.mak

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ff_linux
          path: |
            ff-src/mp/game/FortressForever2013/bin/*.so
            ff-src/mp/game/FortressForever2013/bin/*.dbg
          retention-days: 1
