name: Windows Compiler

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_windows:
    name: Build Windows Binaries
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: fortressforever-2013/fortressforever-src
          path: ff-src
          ref: ${{ vars.CODE_BRANCH }}

      - name: Configure Dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create Project
        run: |
          cd ff-src/mp/src
          devtools/bin/vpc.exe /2013 /ff +game /mksln Game_FF.sln

      - name: Build Project
        run: |
          cd ff-src/mp/src
          devenv Game_FF.sln /Build Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ff_windows
          path: |
            ff-src/mp/game/FortressForever2013/bin/*.dll
            ff-src/mp/game/FortressForever2013/bin/*.pdb
          retention-days: 1

